# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-25 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.PositiveIntegerField()),
                ('interest_reason', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_reason', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Project Title Provided', max_length=255)),
                ('creator', models.CharField(default='No Creator Specified', max_length=255)),
                ('tagline', models.TextField(default='Default Project Tagline', max_length=38)),
                ('content', models.TextField(default='Content', max_length=4000)),
                ('avail_mem', models.BooleanField(default=True)),
                ('sponsor', models.BooleanField(default=False)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('resource', models.TextField(default='*No resources provided*', max_length=4000)),
                ('teamSize', models.IntegerField(default=4)),
                ('meetings', models.TextField(default='')),
                ('readable_meetings', models.TextField(null=True)),
                ('weigh_interest', models.IntegerField(default=1)),
                ('weigh_know', models.IntegerField(default=1)),
                ('weigh_learn', models.IntegerField(default=1)),
                ('desired_skills', models.ManyToManyField(default='', related_name='desired', to='profiles.Skills')),
                ('interest', models.ManyToManyField(default=None, to='projects.Interest')),
                ('members', models.ManyToManyField(through='projects.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_title', models.CharField(default='Default Update Title', max_length=255)),
                ('update', models.TextField(default='Default Update', max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Update',
                'verbose_name_plural': 'Project Updates',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ResourceUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('src_title', models.CharField(default='Default Resource Title', max_length=255)),
                ('src_link', models.URLField(default='Default Resource Link', max_length=2000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Update',
                'verbose_name_plural': 'Resource Updates',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
